// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNMvJgU9Iuajcvd-vysVejtbzaEsyYpdM',
    appId: '1:213379821447:web:a9e5b3ffbcddc22839ed22',
    messagingSenderId: '213379821447',
    projectId: 'baakas-1a4c0',
    authDomain: 'baakas-1a4c0.firebaseapp.com',
    storageBucket: 'baakas-1a4c0.firebasestorage.app',
    measurementId: 'G-SWF4BGDEPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpVDwtNBJT3ecdLQqy8YNzhOFXN1HcRFI',
    appId: '1:213379821447:android:337f5d9d6dc3afa639ed22',
    messagingSenderId: '213379821447',
    projectId: 'baakas-1a4c0',
    storageBucket: 'baakas-1a4c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0BBdeClyCQ5hvwlM4g8aBRZStmnyprsM',
    appId: '1:213379821447:ios:d00f56e4994c339339ed22',
    messagingSenderId: '213379821447',
    projectId: 'baakas-1a4c0',
    storageBucket: 'baakas-1a4c0.firebasestorage.app',
    androidClientId: '213379821447-imtgdkneahlvm40hd6tm0e2g9a1f03q7.apps.googleusercontent.com',
    iosClientId: '213379821447-im138c7aav5mp3jn65hjicr2dgoaesu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.baakasAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyypc4MyqBBneptEWpF17u3s7cu8X4wIY',
    appId: '1:823307041176:ios:7b67fa8db6b2840d0653ed',
    messagingSenderId: '823307041176',
    projectId: 'codingwitht-c6d0f',
    databaseURL: 'https://codingwitht-c6d0f-default-rtdb.firebaseio.com',
    storageBucket: 'codingwitht-c6d0f.appspot.com',
    androidClientId: '823307041176-kun16mo723tugpbptbcbupndhaubv8cn.apps.googleusercontent.com',
    iosClientId: '823307041176-lp36pj2a155ifcmkeil3p2ch72krur3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceAdminPanel.RunnerTests',
  );
}